name: KillRewards
main: com.ericlam.mc.main.KillRewards
version: 1.0
author: Hydranapse_
commands:
  killrewards:
    aliases: [kw,krw]
    description: kill rewards command
permissions:
  kw.admin:
    description: admin permission